from __future__ import annotations

from decimal import Decimal
from pathlib import Path
import time

from repoeval.models import EvalTask, RunnerResult
from repoeval.runners.base import Runner


class MockRunner(Runner):
    name = "mock"

    def run(self, task: EvalTask, repo_path: Path, log_path: Path) -> RunnerResult:
        started = time.monotonic()
        log_path.parent.mkdir(parents=True, exist_ok=True)
        stderr_path = log_path.with_suffix(".err")
        should_fail = bool(task.metadata.get("mock_fail")) or "mock_fail" in task.prompt.lower()

        for expected_file in task.expected_files:
            target = repo_path / expected_file
            target.parent.mkdir(parents=True, exist_ok=True)
            if not target.exists():
                target.write_text(
                    f"Generated by mock runner for task {task.id}\n",
                    encoding="utf-8",
                )

        if should_fail:
            log_path.write_text(f"mock runner failed for {task.id}\n", encoding="utf-8")
            stderr_path.write_text("mock_fail requested\n", encoding="utf-8")
            exit_code = 1
            metadata = {"reason": "mock_fail requested"}
        else:
            log_path.write_text(f"mock runner completed for {task.id}\n", encoding="utf-8")
            stderr_path.write_text("", encoding="utf-8")
            exit_code = 0
            metadata = {}

        return RunnerResult(
            exit_code=exit_code,
            runtime_seconds=time.monotonic() - started,
            cost_usd=Decimal("0"),
            stdout_path=log_path,
            stderr_path=stderr_path,
            metadata=metadata,
        )
